# -*- coding: utf-8 -*-
"""22 new firms (verified 22.09.2026) + 16 leads (unpublished). Cells use the same markup as the comparison table."""
import json, os

V_DA = '<b class="v">Da</b>'
V_ASK = '<b class="v ask">Na upit</b>'
V_NO = '<b class="v no">Ne pominje se</b>'

def rec(slug, name, group, kind, website, domain, city, coverage, offer, price_headline,
        cena, ugradnja, brojilo, skupstina, usluga, verdicts, contact, sources, confidence='visoko', notes='', publish=True):
    return {
        'slug': slug, 'name': name, 'group': group, 'publish': publish, 'is_us': False, 'kind': kind,
        'website': website, 'domain': domain, 'city': city, 'coverage': coverage,
        'offer': offer, 'price_headline': price_headline,
        'cells': {'cena': cena, 'ugradnja': ugradnja, 'brojilo': brojilo, 'skupstina': skupstina, 'usluga': usluga},
        'verdicts': verdicts, 'contact': contact, 'sources': sources,
        'verified': '22.09.2026', 'confidence': confidence, 'notes': notes,
    }

def src(url, label=None, date='22.09.2026'):
    return {'url': url, 'label': label or url.replace('https://', '').replace('http://', '').rstrip('/'), 'date': date}

NEW = [
 # ---------- B: javna cena uređaja, ugradnja na upit ----------
 rec('orion-emobility', 'Orion eMobility (Orion Telekom)', 'B', 'operator',
     'https://oriontelekom.rs/emobility/emobility-fizicka-lica/', 'oriontelekom.rs', 'Beograd', 'cela Srbija',
     'Orion eMobility AC wallbox (ABB Terra AC), 11 i 22 kW, RFID, 4G; operator javne mreže punjača; „Elektro punjači za fizička lica“',
     '11 kW: 99.000 RSD',
     '<b class="pr">11 kW (kabl 5 m, RFID): 99.000 RSD</b><br/>22 kW kabl 5 m, RFID + 4G: 119.000<br/>22 kW utičnica: 109.000<br/>postolje 42.300 · kabl Type 2 7 m 42.600<small>cene na sajtu sa PDV-om, bez montaže</small>',
     V_ASK + '<small>„Montaža, instalacija i puštanje u rad električnog punjača se dodatno naplaćuju, a cena zavisi od lokacije“</small>',
     V_NO,
     V_NO,
     V_NO + '<small>Orion eMobility aplikacija; besplatna RFID kartica za javnu mrežu. Garancija: „minimum 24 meseca“</small>',
     {'ugradnja': 'Na upit', 'brojilo': 'Ne pominje se', 'skupstina': 'Ne pominje se', 'usluga': 'Ne pominje se'},
     {'phone': '011 4100 007', 'email': 'emobility.prodaja@oriontelekom.rs'},
     [src('https://oriontelekom.rs/emobility/emobility-fizicka-lica/'), src('https://oriontelekom.rs/emobility/aplikacija/')],
     notes='Telekom-operator sa sopstvenim naplatnim sistemom i aplikacijom — ušao u prodaju kućnih punjača fizičkim licima.'),
 rec('provision', 'ProVision (SMIT Media)', 'B', 'distributer',
     'https://provision.rs/punjaci-za-elektricne-automobile/', 'provision.rs', 'Novi Sad / Subotica', 'Vojvodina',
     'Circontrol eHome 5, eNext T, eVolve Smart S; Teltonika; servis ABB i Webasto; od 2017; sestrinski brend firme SMIT (Srbobran)',
     'Circontrol eHome 5 (7,4 kW): 107.000 RSD',
     '<b class="pr">Circontrol eHome 5, 7,4 kW: 107.000 RSD</b><br/>eNext T, eVolve Smart S — cena na upit<small>„preporučene maloprodajne cene sa PDV-om“; „uz punjač se ne dobija kabl za punjenje“</small>',
     V_ASK + '<small>„U saradnji sa SMIT MEDIA nudimo stručnu montažu“ — Novi Sad, Subotica i okolina; cena nije objavljena</small>',
     V_NO,
     V_NO,
     V_NO + '<small>isporuka 2–5 radnih dana. Garancija: trajanje nije navedeno</small>',
     {'ugradnja': 'Na upit', 'brojilo': 'Ne pominje se', 'skupstina': 'Ne pominje se', 'usluga': 'Ne pominje se'},
     {'phone': '062 300 840, 021 735 907', 'email': 'office@provision.rs'},
     [src('https://provision.rs/prodaja/circontrol-ehome-5-punjac/'), src('https://provision.rs/punjaci-za-elektricne-automobile/')]),
 # ---------- C: samo uređaj ----------
 rec('voltech', 'Voltech Srbija', 'C', 'prodavnica',
     'https://voltech.rs/product-category/punjaci-za-ev/wallbox-od-7-22kw/', 'voltech.rs', 'Čoka', 'cela Srbija (online)',
     'Sopstveni brend Voltech (EVX07/11/22) + Honor, BENY, Gemini; wallbox 7,4–22 kW, deo modela OCPP/WiFi; „preko dve godine iskustva“',
     'EVX11 11 kW: 48.000 RSD',
     '<b class="pr">EVX11 11 kW: 48.000 RSD</b><br/>Gemini 11 kW: 60.000 · Honor11 + DLB: 68.000<br/>EVX07 7,4 kW: 38.000<br/>22 kW: 55.000–80.000 · BENY 22 kW OCPP: 70.000<small>PDV-status na sajtu nije označen; iste cene i na eponuda.com</small>',
     V_NO + '<small>samo prodaja uređaja</small>',
     V_NO,
     V_NO,
     V_NO + '<small>„Smart konekcija“ — daljinsko praćenje i upravljanje na delu modela. Garancija: nije navedena na stranici kategorije</small>',
     {'ugradnja': 'Ne pominje se', 'brojilo': 'Ne pominje se', 'skupstina': 'Ne pominje se', 'usluga': 'Ne pominje se'},
     {'phone': '+381 65 55 88 007', 'email': 'voltech.srbija@gmail.com'},
     [src('https://voltech.rs/product-category/punjaci-za-ev/wallbox-od-7-22kw/'), src('https://www.eponuda.com/punjaci-za-elektricne-automobile-cene')],
     notes='Najniža javna cena uređaja od 11 kW u Srbiji na dan provere.'),
 rec('sp-solar', 'SP Solar', 'C', 'solar',
     'https://spsolar.rs/proizvod/punjac-za-elektricna-vozila-sungrow-ac011e-01/', 'spsolar.rs', 'Pirot', 'cela Srbija (online)',
     'Solarne elektrane + web-shop; Sungrow AC011E-01 11 kW, kabl 7 m, IP65, OCPP 1.6, RFID i aplikacija',
     'Sungrow 11 kW: 70.092 RSD',
     '<b class="pr">Sungrow AC011E-01, 11 kW: 70.092 RSD</b><small>sa PDV-om; isti model kod ChargeGo košta 90.000</small>',
     V_NO + '<small>na stranici proizvoda se ne pominje; firma inače montira solarne sisteme</small>',
     V_NO,
     V_NO,
     V_NO + '<small>OCPP 1.6, RFID kartica, mobilna aplikacija. Garancija: nije navedena</small>',
     {'ugradnja': 'Ne pominje se', 'brojilo': 'Ne pominje se', 'skupstina': 'Ne pominje se', 'usluga': 'Ne pominje se'},
     {'phone': '+381 61 660 9999'},
     [src('https://spsolar.rs/proizvod/punjac-za-elektricna-vozila-sungrow-ac011e-01/')]),
 rec('it-home', 'IT-Home', 'C', 'solar',
     'https://store.it-home.rs/product-category/ev-punjaci/', 'it-home.rs', 'Vranje', 'cela Srbija (online)',
     'Solarni sistemi i pametna kuća; distribucija Teltonika TeltoCharge 11 i 22 kW (WiFi/Bluetooth ili GSM, NFC)',
     'TeltoCharge 11 kW: 93.600 RSD',
     '<b class="pr">TeltoCharge 11 kW: 93.600 RSD</b><br/>TeltoCharge 22 kW: 128.700<small>sa PDV-om</small>',
     V_NO + '<small>na stranicama proizvoda se ne pominje</small>',
     V_NO,
     V_NO,
     V_NO + '<small>Garancija: 3 godine</small>',
     {'ugradnja': 'Ne pominje se', 'brojilo': 'Ne pominje se', 'skupstina': 'Ne pominje se', 'usluga': 'Ne pominje se'},
     {'email': 'info@it-home.rs'},
     [src('https://store.it-home.rs/product-category/ev-punjaci/'), src('https://www.it-home.rs/ev-punjaci/')]),
 rec('andreja', 'Andreja d.o.o. (solar-shop.rs)', 'C', 'prodavnica',
     'https://www.solar-shop.rs/', 'solar-shop.rs', 'Temerin', 'cela Srbija (online)',
     'Web-shop solarne opreme i akumulatora; Growatt THOR 11/22 kW, Victron EVCS 22 kW, Huawei SCharger 22 kW; integracija sa solarnim sistemom',
     'Growatt THOR 22 kW: 72.000 RSD',
     '<b class="pr">Growatt THOR 22 kW: 72.000 RSD</b> (bilo 118.800)<br/>Growatt THOR 11 kW: 101.880<br/>Victron 22 kW: 76.800<br/>Huawei SCharger 22 kW: 118.800 (nema na stanju)<small>PDV-status na sajtu nije označen</small>',
     V_NO + '<small>samo prodaja; besplatna dostava od 4.000 RSD</small>',
     V_NO,
     V_NO,
     V_NO + '<small>WiFi, aplikacija, rad uz solarnu elektranu. Garancija: 25 meseci (THOR 22 kW)</small>',
     {'ugradnja': 'Ne pominje se', 'brojilo': 'Ne pominje se', 'skupstina': 'Ne pominje se', 'usluga': 'Ne pominje se'},
     {'phone': '021/840-666, Viber 060 0840 666', 'email': 'solar@andreja.co.rs'},
     [src('https://www.solar-shop.rs/kupi/growatt-thor-22kw-as-p-v1-ac-punjac-za-elektro-vozila-1263'), src('https://www.akumulator-shop.rs/punjaci-za-ev-vozila')]),
 rec('wise-smart-home', 'WISE Smart Home', 'C', 'prodavnica',
     'https://wifioprema.rs/product-category/wifi-pametna-oprema-pametna-kuca/punjaci-za-elektricna-vozila/', 'wifioprema.rs', 'Beograd, Novi Sad', 'cela Srbija',
     'Prodavnice pametne kuće u Beogradu i Novom Sadu; sopstveni brend Wise (Tuya / Smart Life): zidni WSCP02/07/08, prenosni, dvostruki WSCP10',
     'WSCP08 7 kW: 62.890 RSD',
     '<b class="pr">WSCP08 7 kW: 62.890 RSD</b><br/>WSCP02: 67.390–82.390 · WSCP07: 62.390–72.390<br/>prenosni 3,5–7 kW: 21.690–52.990<small>PDV-status na sajtu nije označen (maloprodaja)</small>',
     V_NO,
     V_NO,
     V_NO,
     V_NO + '<small>Smart Life aplikacija (struja, napon, raspored, istorija); OCPP se ne pominje. Garancija: nije navedena</small>',
     {'ugradnja': 'Ne pominje se', 'brojilo': 'Ne pominje se', 'skupstina': 'Ne pominje se', 'usluga': 'Ne pominje se'},
     {'phone': '+381 66 534 35 79 (BG), +381 62 39 19 14 (NS)', 'email': 'info@wise-smarthome.rs'},
     [src('https://wifioprema.rs/product-category/wifi-pametna-oprema-pametna-kuca/punjaci-za-elektricna-vozila/')]),
 rec('elektronapon', 'Elektronapon', 'C', 'prodavnica',
     'https://elektronapon.rs/', 'elektronapon.rs', 'Subotica', 'Subotica / online',
     'Elektrotehnička prodavnica; ABB Terra AC 7 kW (jednofazni, RFID) i 22 kW (trofazni)',
     'ABB Terra AC 7 kW: 97.977 RSD',
     '<b class="pr">ABB Terra AC W7, 7 kW: 97.977 RSD</b> (81.647,50 bez PDV)<br/>ABB Terra AC W22, 22 kW: 111.972<small>sa PDV-om; 7 kW „trenutno nema na stanju“, 22 kW po narudžbini; bez kabla</small>',
     V_NO,
     V_NO,
     V_NO,
     V_NO + '<small>Garancija: 2 godine</small>',
     {'ugradnja': 'Ne pominje se', 'brojilo': 'Ne pominje se', 'skupstina': 'Ne pominje se', 'usluga': 'Ne pominje se'},
     {'phone': '+381 24 4-150-150'},
     [src('https://elektronapon.rs/sr/punjac-tac-w7-t-r-0-terra-zidna-abb-tip2-1-fazni32a-rfid-ac/proizvod/2304')]),
 rec('elektro-centar-nais', 'Elektro Centar Nais', 'C', 'prodavnica',
     'https://www.ecn.rs/evlink-home-jednostavno-punjenje-ev-vozila-kod-kuce', 'ecn.rs', 'Niš', 'Niš / online',
     'Veleprodaja i maloprodaja elektromaterijala; Schneider EVlink Home 3,7 / 7,4 / 11 kW, sa utičnicom ili kablom; load-shedder',
     'EVlink Home 11 kW: 120.360 RSD',
     '<b class="pr">EVlink Home 11 kW (utičnica): 120.360 RSD</b><br/>3,7 kW: 110.920 · 7,4 kW: 114.460<br/>sa kablom 5 m: 125.080–141.600<br/>load-shedder: 21.240–22.080<small>PDV-status na stranici nije označen</small>',
     V_NO + '<small>inženjerska podrška; montaža se ne pominje</small>',
     V_NO,
     V_NO,
     V_NO + '<small>Garancija: nije navedena</small>',
     {'ugradnja': 'Ne pominje se', 'brojilo': 'Ne pominje se', 'skupstina': 'Ne pominje se', 'usluga': 'Ne pominje se'},
     {'phone': '+381 18 51 63 64', 'email': 'slobodan@elektrocentarnais.rs'},
     [src('https://www.ecn.rs/evlink-home-jednostavno-punjenje-ev-vozila-kod-kuce')], confidence='srednje'),
 rec('ep-solutions', 'EP Solutions (Electro Pneumatic Solutions)', 'C', 'distributer',
     'https://www.ep-solutions.rs/', 'ep-solutions.rs', 'Beograd', 'cela Srbija (B2B web-shop)',
     'Industrijski distributer Schneider Electric sa web-shopom; EVlink Wallbox 11 kW (T2 utičnica) i 22 kW',
     'EVlink Wallbox 11 kW: 157.028 RSD',
     '<b class="pr">EVlink Wallbox 11 kW: 157.028,40 RSD</b><small>PDV-status nije označen; „out of stock“ na dan provere</small>',
     V_NO,
     V_NO,
     V_NO,
     V_NO + '<small>Garancija: nije navedena</small>',
     {'ugradnja': 'Ne pominje se', 'brojilo': 'Ne pominje se', 'skupstina': 'Ne pominje se', 'usluga': 'Ne pominje se'},
     {'phone': '+381 11 257 19 22', 'email': 'office@ep-solutions.rs'},
     [src('https://www.ep-solutions.rs/en/schneider-electric-evlink-wallbox-11-kw-t2-uticnica-stanice-za-punjenje-evh2s11p02k')], confidence='srednje'),
 rec('praktiker-elektrowebshop', 'Praktiker (elektrowebshop.rs)', 'C', 'prodavnica',
     'https://elektrowebshop.rs/category/punjaci-za-elektricna-vozila', 'elektrowebshop.rs', 'Nova Pazova', 'cela Srbija (online)',
     'Web-shop elektroopreme; Noark punjač 22 kW (400 V, 32 A) i Noark oprema za merenje struje',
     'Noark 22 kW: 99.990 RSD',
     '<b class="pr">Noark 22 kW: 99.990 RSD</b><br/>Noark oprema za merenje struje: 22.999<small>PDV-status nije označen</small>',
     V_NO,
     V_NO,
     V_NO,
     V_NO + '<small>Garancija: nije navedena</small>',
     {'ugradnja': 'Ne pominje se', 'brojilo': 'Ne pominje se', 'skupstina': 'Ne pominje se', 'usluga': 'Ne pominje se'},
     {'phone': '062 267 147', 'email': 'info@elektrowebshop.rs'},
     [src('https://elektrowebshop.rs/category/punjaci-za-elektricna-vozila')], confidence='srednje'),
 # ---------- D: bez javne cene ----------
 rec('union-electronics-avtera', 'Union Electronics (AVTERA)', 'D', 'distributer',
     'https://www.unionelectronics.rs/proizvodi/elektricni-punjaci/', 'unionelectronics.rs', 'Beograd', 'cela Srbija',
     'Zastupnik brenda UNION (proizvodi Vestel EVC04); model EVC04-AC22SWDLMID: do 22 kW, ugrađen MID brojač, LCD 4,3″, kabl 5 m, WiFi, LTE, NFC',
     'na upit',
     '<b class="v ask">Na upit</b><small>na sajtu bez cene; na marketplace-u Bazzar: EVC04-AC7 (7 kW) 88.690 RSD (prodavac Avtera)</small>',
     V_ASK + '<small>„instalirani i servisirani od strane naših sertifikovanih profesionalaca“; cena nije objavljena</small>',
     '<b class="v">Da, u uređaju</b><small>„dolazi sa ugrađenim MID metrom“ — jedini od novih igrača koji MID ističe u opisu; obračun kao usluga se ne pominje</small>',
     V_NO,
     V_NO + '<small>stranica /garancija/ postoji, trajanje nije navedeno u opisu proizvoda</small>',
     {'ugradnja': 'Na upit', 'brojilo': 'Da, u uređaju', 'skupstina': 'Ne pominje se', 'usluga': 'Ne pominje se'},
     {'phone': '+381 11 41 42 090', 'email': 'info@avtera.rs'},
     [src('https://www.unionelectronics.rs/proizvodi/elektricni-punjaci/'), src('https://bazzar.rs/c/punjaci-za-elektricna-vozila')], confidence='srednje'),
 rec('mda-e-technology', 'MDA E-Technology', 'D', 'distributer',
     'https://www.mdaetechnology.rs/proizvodi-elektro-punjaci/', 'mdaetechnology.rs', 'Beograd', 'cela Srbija',
     'Ekskluzivni distributer španskog Orbis (Viaris UNI 3,7–22 kW, Viaris combi, city); OCPP-J; MID opciono; pominje stambene zgrade i garaže investitora',
     'na upit',
     '<b class="v ask">Na upit</b><small>cene nisu objavljene, forma za konsultaciju</small>',
     V_NO + '<small>samo forma za konsultaciju</small>',
     '<b class="v">MID opciono</b><small>„merenje i snimanje naelektrisane energije“; MID kao opcija za sve modele; obračun kao usluga se ne pominje</small>',
     V_NO + '<small>stambene zgrade se pominju kao primena, ne kao usluga sa papirima</small>',
     V_NO + '<small>Garancija: nije navedena</small>',
     {'ugradnja': 'Ne pominje se', 'brojilo': 'MID opciono', 'skupstina': 'Ne pominje se', 'usluga': 'Ne pominje se'},
     {'phone': '+381 63 244 211', 'email': 'office@mdaetechnology.rs'},
     [src('https://www.mdaetechnology.rs/proizvodi-elektro-punjaci/')], confidence='srednje'),
 rec('ev-charging-solutions', 'EV Charging Solutions (Europlus System)', 'D', 'distributer',
     'https://www.evchargingsolutions.rs/', 'evchargingsolutions.rs', 'Beograd', 'cela Srbija',
     'Distributer i integrator: Kempower, Alfen (Eve Single/Double), NRGkick, Wallbox Pulsar Pro/Max, Juice, Zaptec, Exicom; klijenti Rivian, Volvo Trucks, Premier Taxi',
     'na upit',
     '<b class="v ask">Na upit</b><small>„Za ponudu punjača i kompletne instalacije možete nas kontaktirati“</small>',
     V_ASK + '<small>„nudimo standardnu garanciju i paket usluge montaže“; cena nije objavljena</small>',
     V_NO,
     V_NO,
     V_NO + '<small>„standardna garancija“, trajanje nije navedeno</small>',
     {'ugradnja': 'Na upit', 'brojilo': 'Ne pominje se', 'skupstina': 'Ne pominje se', 'usluga': 'Ne pominje se'},
     {'email': 'info@evchargingsolutions.rs'},
     [src('https://www.evchargingsolutions.rs/'), src('https://www.evchargingsolutions.rs/category/ev-punjaci/')], confidence='srednje'),
 rec('energy-net', 'Energy Net', 'D', 'instalater',
     'https://www.energynet.rs/resenja-za-dom/obnovljivi-izvori/elektro-punjaci/', 'energynet.rs', 'Novi Sad', 'cela Srbija (mreža instalatera)',
     'HVAC i OIE integrator sa 30+ godina; punjač EVC16 do 22 kW sa aplikacijom; „više od 200 sertifikovanih instalatera u Republici Srbiji“ obučenih u sopstvenoj akademiji',
     'na upit',
     '<b class="v ask">Na upit</b><small>katalog „uskoro“, cene nisu objavljene</small>',
     V_DA + '<small>preko mreže od 200+ sertifikovanih instalatera; cena nije objavljena</small>',
     V_NO,
     V_NO,
     '<b class="v">Produžena garancija</b><small>„produženi garantni rok za instalacije od strane Energy Net instalatera“ — trajanje nije navedeno; mesečna usluga se ne pominje</small>',
     {'ugradnja': 'Da', 'brojilo': 'Ne pominje se', 'skupstina': 'Ne pominje se', 'usluga': 'Produžena garancija'},
     {'phone': '066/090 090', 'email': 'office@energynet.rs'},
     [src('https://www.energynet.rs/resenja-za-dom/obnovljivi-izvori/elektro-punjaci/')], confidence='srednje',
     notes='Strukturno najbliži model mreži nezavisnih električara sa produženom garancijom.'),
 rec('veming', 'Veming', 'D', 'instalater',
     'https://veming.rs/kucni-punjaci/', 'veming.rs', 'Čačak', 'zapadna Srbija',
     'Elektroinstalaterska firma („inteligentne elektroinstalacije“); Enelion Wallbox i Wallbox Duo (7,4 ili 22 kW), EV Stream; OCPP 1.6, GSM/WiFi/Ethernet, RFID, balansiranje; regionalni partner Emobility',
     'na upit',
     '<b class="v ask">Na upit</b>',
     V_DA + '<small>elektromontaža je delatnost firme; cena nije objavljena</small>',
     V_NO,
     V_NO,
     V_NO + '<small>Garancija: nije navedena</small>',
     {'ugradnja': 'Da', 'brojilo': 'Ne pominje se', 'skupstina': 'Ne pominje se', 'usluga': 'Ne pominje se'},
     {'phone': '+381 32 40051', 'email': 'office@veming.rs'},
     [src('https://veming.rs/kucni-punjaci/'), src('https://emobility.rs/partneri/')], confidence='srednje'),
 rec('obd2-evchargers', 'OBD2 d.o.o. (evchargers.rs)', 'D', 'distributer',
     'https://evchargers.rs/punjaci-za-elektricne-automobile/', 'evchargers.rs', 'Beograd', 'Srbija i region',
     'Zastupnik Autel za Srbiju i region; Autel MaxiCharger AC Wallbox (kućna upotreba), DC Wallbox, DC Fast; dijagnostička oprema',
     'na upit',
     '<b class="v ask">Na upit</b><small>cene nisu na stranici kategorije</small>',
     V_NO,
     V_NO,
     V_NO,
     V_NO + '<small>Autel aplikacija. Garancija: nije navedena</small>',
     {'ugradnja': 'Ne pominje se', 'brojilo': 'Ne pominje se', 'skupstina': 'Ne pominje se', 'usluga': 'Ne pominje se'},
     {'phone': '+381 63 800 800 7', 'email': 'info@evchargers.rs'},
     [src('https://evchargers.rs/punjaci-za-elektricne-automobile/')], confidence='srednje'),
 rec('kibost-car', 'KiBOST Car', 'D', 'instalater',
     'https://kibostcar.com/punjaci-za-elektricne-automobile/', 'kibostcar.com', 'Beograd / Novi Sad', 'Srbija',
     'Rent-a-car i uvoz EV; „iznajmljivanje i prodaja punjača“ različitih snaga; za vlasnike lokacija: renta 1,99 €/dan ili podela prihoda',
     'na upit',
     '<b class="v ask">Na upit</b><small>modeli, snage i cene u RSD nisu objavljeni</small>',
     V_DA + '<small>„profesionalna instalacija punjača na vašoj lokaciji“; cena nije objavljena</small>',
     V_NO,
     V_NO,
     '<b class="v ask">Renta za lokacije</b><small>„simbolična mesečna renta od 1,99 € po danu“ ili podela prihoda — za vlasnike lokacija, ne za stanare; „redovno proveravanje stanja punjača“</small>',
     {'ugradnja': 'Da', 'brojilo': 'Ne pominje se', 'skupstina': 'Ne pominje se', 'usluga': 'Renta za lokacije'},
     {'phone': '+381 65 44 333 11', 'email': 'office@kibostcar.com'},
     [src('https://kibostcar.com/punjaci-za-elektricne-automobile/')], confidence='srednje'),
 rec('eko-term', 'Eko-Term', 'D', 'solar',
     'https://eko-term.co.rs/', 'eko-term.co.rs', 'Senta', 'severna Vojvodina',
     'Grejanje, klimatizacija i solarni sistemi; Huawei SCharger-7KS-S0 (7,4 kW, jednofazni), FusionSolar aplikacija',
     'na upit',
     '<b class="v ask">Na upit</b>',
     V_NO + '<small>„instalaciju mora izvesti kvalifikovani električar“; sopstvena montaža se ne pominje</small>',
     V_NO,
     V_NO,
     V_NO + '<small>Garancija: nije navedena</small>',
     {'ugradnja': 'Ne pominje se', 'brojilo': 'Ne pominje se', 'skupstina': 'Ne pominje se', 'usluga': 'Ne pominje se'},
     {'phone': '+381 24 812 445', 'email': 'info@eko-term.co.rs'},
     [src('https://eko-term.co.rs/en/product/ev-charger-3/')], confidence='srednje'),
 rec('conseko', 'Conseko', 'D', 'distributer',
     'https://conseko.rs/', 'conseko.rs', 'Beograd', 'Srbija',
     'Inženjerska firma, zastupnik evropskih proizvođača; Fronius Wattpilot Go 11J / Home 11J; web-shop prodaja.conseko.rs nije radio na dan provere',
     'na upit',
     '<b class="v ask">Na upit</b>',
     V_NO,
     V_NO,
     V_NO,
     V_NO + '<small>Fronius aplikacija. Garancija: nije navedena</small>',
     {'ugradnja': 'Ne pominje se', 'brojilo': 'Ne pominje se', 'skupstina': 'Ne pominje se', 'usluga': 'Ne pominje se'},
     {'phone': '+381 11 2971 995', 'email': 'info@conseko.rs'},
     [src('https://conseko.rs/en/')], confidence='nisko'),
 # ---------- E: samo ugradnja (električari) ----------
 rec('elektricar-nis', 'Električar Niš', 'E', 'elektricar',
     'https://www.niselektricar.rs/cenovnik', 'niselektricar.rs', 'Niš', 'Niš i okolina',
     'Električarski servis sa javnim cenovnikom; „postavljanje kućnih punjača za električna vozila, sa posebnim vodom i osiguračem prilagođenim snazi punjenja“; uređaj ne prodaje',
     'ugradnja: 12.000–20.000 RSD',
     '<b class="v no">Uređaj ne prodaje</b><small>montira punjač koji donese kupac</small>',
     '<b class="v">Da — javna cena</b><small>ugradnja kućnog punjača 12.000–20.000 RSD; poseban vod 8.000–18.000; ugradnja u garaži ili dvorištu 15.000–25.000; konsultacije od 3.000; izlazak u Nišu besplatan (PDV-status nije označen)</small>',
     V_NO,
     V_NO,
     V_NO + '<small>„garancija na sve radove“, trajanje nije navedeno</small>',
     {'ugradnja': 'Da — javna cena', 'brojilo': 'Ne pominje se', 'skupstina': 'Ne pominje se', 'usluga': 'Ne pominje se'},
     {'phone': '063 133 7373', 'email': 'kontakt@niselektricar.rs'},
     [src('https://www.niselektricar.rs/cenovnik'), src('https://www.niselektricar.rs/')],
     notes='Jedini javni cenovnik rada za ugradnju punjača koji smo našli u Srbiji.'),
 rec('handyman', 'Handyman – Moj Majstor', 'E', 'elektricar',
     'https://handyman.rs/elektricar/elektricni-automobili-instalacija-punjaca-u-vasem-domacinstvu/', 'handyman.rs', 'Beograd', 'Beograd',
     'Servis majstora i električara; posebna usluga „Električni automobili: instalacija punjača u vašem domaćinstvu“; uređaj ne prodaje',
     'na upit',
     '<b class="v no">Uređaj ne prodaje</b>',
     V_ASK + '<small>„najpovoljnija ponuda“ na upit; stranica /cenovnik/ ne radi</small>',
     V_NO,
     V_NO,
     V_NO + '<small>„usluga instalacije često dolazi sa garancijom kvaliteta“ — trajanje nije navedeno</small>',
     {'ugradnja': 'Na upit', 'brojilo': 'Ne pominje se', 'skupstina': 'Ne pominje se', 'usluga': 'Ne pominje se'},
     {'phone': '064 00 55 999', 'email': 'office@handyman.rs', 'other': 'WhatsApp / Viber'},
     [src('https://handyman.rs/elektricar/elektricni-automobili-instalacija-punjaca-u-vasem-domacinstvu/')], confidence='srednje'),
]

LEADS = [
 ('tesla-sistemi-energetika', 'Tesla sistemi „Energetika“', 'energetika.co.rs', 'Novi Beograd', 'WallBox Smart 22 kW, OCPP, RFID, „smart metering“, cilja stambene blokove i biznis; B2B profil (UPS, telekom); cena nije objavljena'),
 ('procharge', 'ProCharge', 'pro-charge.rs', 'Pančevo', 'brzi DC punjači za biznis (Hyatt, Orion, Azotara); kućni AC se ne pominje'),
 ('jakov-sistem', 'Jakov Sistem', 'jakov.rs', 'Beograd / Niš', 'Wallbox Copper SB 22 kW i ABB Terra AC u katalogu, cene skrivene („nije na stanju“)'),
 ('lampomanija', 'Lampomanija', 'lampomanija.rs', 'Novi Sad', 'na eponuda.com: Platinet 11 kW i Immax 22 kW po 41.399 RSD, prenosni 15.399–40.799; na sajtu kategorija nije nađena'),
 ('big-bang', 'Big Bang', 'bigbang.rs', 'Srbija', 'na eponuda.com jedan Union EVC04 7 kW za 31.249 RSD; na sajtu kategorija nije nađena'),
 ('network-shop-bazzar', '„Network shop“ (Bazzar)', 'bazzar.rs', '—', 'ABB Terra AC 22 kW RFID 4G za 275.559 RSD na marketplace-u; prodavac nije identifikovan'),
 ('tehnoducan', 'Tehnodućan', 'tehnoducan.rs', '—', 'ABB Terra AC W22/W11/W7 u kategoriji; stranice proizvoda bez cene'),
 ('sirotin', 'Sirotin Šabac', 'sirotin.rs', 'Šabac', 'veleprodaja elektromaterijala; Schneider EVlink u pretrazi, bez cena na sajtu'),
 ('elektroleum', 'Elektroleum', 'elektroleum.rs', '—', 'Schneider EVB3S22N41 22 kW; sajt nije bio dostupan (403)'),
 ('gramper', 'GrampeR', 'gramper.com', 'Beograd', 'distributer Noark (po industrija.rs); na sajtu EV-sekcija nije nađena'),
 ('energize', 'Energize', 'energize.rs', 'Beograd / Barajevo', '„punjači vodećih svetskih proizvođača“ + Energize DC (PDF); modeli i cene nisu objavljeni'),
 ('elmik-inzenjering', 'Elmik Inženjering', 'elmik.rs', 'Mali Zvornik', 'meni „Solarni paneli i Punjači“, bez detalja'),
 ('schrack-technik', 'Schrack Technik Srbija', 'schrack.rs', 'Beograd', 'i-CHARGE CION u pretrazi; stranice proizvoda 404'),
 ('antenall', 'Antenall', 'antenall.rs', 'Beograd', 'distributer Teltonika (mreže); TeltoCharge nije pomenut na sajtu'),
 ('digital-hajdukovic', 'Digital Hajduković', 'digital.rs', '—', 'EVD02-11RD 11 kW u pretrazi; domen na parking-stranici'),
 ('az-group', 'AZ Group', 'azgroupdoo.com', 'Sombor', 'partner Emobility „za EV instalacije u severnoj Srbiji“; na sopstvenom sajtu EV se ne pominje'),
]

os.makedirs('content/firme', exist_ok=True)
for r in NEW:
    with open(f"content/firme/{r['slug']}.json", 'w', encoding='utf-8') as f:
        json.dump(r, f, ensure_ascii=False, indent=1)
for slug, name, domain, city, note in LEADS:
    r = {'slug': slug, 'name': name, 'group': 'L', 'publish': False, 'is_us': False, 'kind': 'trag',
         'website': 'https://' + domain, 'domain': domain, 'city': city, 'coverage': '', 'offer': note,
         'price_headline': '', 'cells': {}, 'verdicts': {}, 'contact': {}, 'sources': [],
         'verified': '22.09.2026', 'confidence': 'nisko', 'notes': 'Trag — proveriti pozivom pre objave.'}
    with open(f"content/firme/{slug}.json", 'w', encoding='utf-8') as f:
        json.dump(r, f, ensure_ascii=False, indent=1)
print('new', len(NEW), 'leads', len(LEADS))
