# -*- coding: utf-8 -*-
"""Ring 2 — public charging operators, hosts and free chargers in Serbia (content/operateri/*.json).
Facts, dates and confidence levels follow the 22.09.2026 research (BlokVolt_Agregator_Istrazivanje_Javno_Punjenje)."""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / 'content' / 'operateri'
OUT.mkdir(parents=True, exist_ok=True)
D = '22.09.2026'

def src(url, label, date=D):
    return {'url': url, 'label': label, 'date': date}

OPS = [
 {
  'slug': 'chargego', 'name': 'Charge&GO (MT-KOMEX)', 'kind': 'cpo', 'order': 1,
  'short': 'Komercijalna mreža javnih punjača — operator mreže (CPO) i aplikacija za naplatu (eMSP): 79 punjača na 68 lokacija prema brojačima operatera. Ista firma kao ChargeGo / elektropunjaci.com iz registra kućnih punjača.',
  'website': 'https://chargego.rs/', 'domain': 'chargego.rs', 'app': 'Charge&GO (iOS/Android) · veb-klijent client.chargego.rs',
  'city': 'Beograd', 'coverage': 'cela Srbija (koridori E75/E70, Beograd, Novi Sad, Niš, Kragujevac, Čačak, Subotica); Severna Makedonija, BiH',
  'network': '79 punjača · 68 lokacija · 135 konektora (brojači na chargego.rs, stanje 31.07.2025, provereno 22.09.2026)',
  'power': 'AC 22 kW – DC 240 kW (tipično DC 50–150 kW); domaćini: OMV (18 lokacija), NIS/Gazprom, Stop Shop, BIG, Promenada, Airport City',
  'billing': 'Po minutu punjenja, PDV uračunat. Cena zavisi od snage punjača: u aplikaciji 22.09.2026 od 16,67 RSD/min (AC 22 kW) do 126,67 RSD/min (DC 240 kW). Na računu u aplikaciji stoje trajanje, isporučeni kWh, neto iznos i PDV. Ranije je zabeležena i razlika u ceni za registrovane i neregistrovane korisnike (2025).',
  'verdicts': {'cenovnik': 'Nije objavljen — samo u aplikaciji', 'naplata': 'Po minutu', 'kwh': 'Ne', 'idle': '5 RSD/min posle 15 min'},
  'vclass': {'cenovnik': 'ask', 'naplata': 'ask', 'kwh': 'no', 'idle': 'yes'},
  'prices': [
   {'what': 'AC 22 kW — HIT Auto (Staro Sajmište), MT-Komex, Termovent, TC Promenada Novi Sad, B2 Sun Spot Mokrin', 'value': '16,67 RSD/min (1.000 RSD/sat)', 'date': D, 'source': 'aplikacija Charge&GO — snimak ekrana redakcije', 'url': 'https://chargego.rs/', 'confidence': 'primarni izvor (aplikacija)'},
   {'what': 'DC 30 kW — NCR, Španskih boraca 75, Beograd', 'value': '33,33 RSD/min', 'date': D, 'source': 'aplikacija Charge&GO — snimak ekrana redakcije', 'url': 'https://chargego.rs/', 'confidence': 'primarni izvor (aplikacija)'},
   {'what': 'DC 50 kW — OMV Ada Ciganlija, Beograd', 'value': '33,33 RSD/min', 'date': D, 'source': 'aplikacija Charge&GO — snimak ekrana redakcije', 'url': 'https://chargego.rs/', 'confidence': 'primarni izvor (aplikacija)'},
   {'what': 'DC 60 kW — BIG Rakovica, Stop Shop Borča, OMV Dragoslava Srejovića', 'value': '58,33 RSD/min', 'date': D, 'source': 'aplikacija Charge&GO — snimak ekrana redakcije', 'url': 'https://chargego.rs/', 'confidence': 'primarni izvor (aplikacija)'},
   {'what': 'DC 110–120 kW — OMV Kneževac, OMV Borska, BIG Karaburma, OMV Vranje, OMV Palić, Stop Shop Sombor', 'value': '101,67 RSD/min', 'date': D, 'source': 'aplikacija Charge&GO — snimak ekrana redakcije', 'url': 'https://chargego.rs/', 'confidence': 'primarni izvor (aplikacija)'},
   {'what': 'DC 150–180 kW — Super Vero Novi Sad, BIG Zrenjanin, OMV Bačka Topola', 'value': '114,17 RSD/min', 'date': D, 'source': 'aplikacija Charge&GO — snimak ekrana redakcije', 'url': 'https://chargego.rs/', 'confidence': 'primarni izvor (aplikacija)'},
   {'what': 'DC 240 kW — OMV Zemun park, Beograd', 'value': '126,67 RSD/min', 'date': D, 'source': 'aplikacija Charge&GO — snimak ekrana redakcije', 'url': 'https://chargego.rs/', 'confidence': 'primarni izvor (aplikacija)'},
   {'what': 'Račun: OMV Zemun park, DC 240 kW', 'value': '760,02 RSD za 12,74 kWh ≈ 60 RSD/kWh', 'date': 'septembar 2026', 'source': 'račun u aplikaciji Charge&GO (punjenje redakcije)', 'url': 'https://chargego.rs/', 'confidence': 'primarni izvor (račun)'},
   {'what': 'Račun: OMV Zemun park, DC 240 kW', 'value': '1.013,36 RSD za 17,96 kWh ≈ 56 RSD/kWh', 'date': 'septembar 2026', 'source': 'račun u aplikaciji Charge&GO (punjenje redakcije)', 'url': 'https://chargego.rs/', 'confidence': 'primarni izvor (račun)'},
   {'what': 'Račun: Super Vero Novi Beograd, DC', 'value': '1.198,85 RSD za 27,89 kWh ≈ 43 RSD/kWh', 'date': 'septembar 2026', 'source': 'račun u aplikaciji Charge&GO (punjenje redakcije)', 'url': 'https://chargego.rs/', 'confidence': 'primarni izvor (račun)'},
   {'what': 'Račun: BS Gazprom Stari Banovci, DC (tarifa 58,33 RSD/min)', 'value': '349,98 RSD za 4,43 kWh ≈ 79 RSD/kWh', 'date': 'avgust 2026', 'source': 'račun u aplikaciji Charge&GO (punjenje redakcije)', 'url': 'https://chargego.rs/', 'confidence': 'primarni izvor (račun)'},
   {'what': 'Istorija: DC 150 kW, Super Vero Novi Sad', 'value': '99 RSD/min (registrovani) · 118 RSD/min (neregistrovani)', 'date': 'februar 2025', 'source': 'komentar korisnika, evfix.rs', 'url': 'https://evfix.rs/stanice-za-punjenje-ev/naplata-punjenja/mapa-punjaca-novi-sad/', 'confidence': 'korisnički podatak'},
   {'what': 'Istorija: DC ~120 kW', 'value': '81–97,20 RSD/min', 'date': 'avgust 2023', 'source': 'forum.beobuild.rs', 'url': 'https://forum.beobuild.rs/threads/električna-vozila-i-punjači.3889/page-64', 'confidence': 'korisnički podatak'},
   {'what': 'Istorija: AC 11/22 kW', 'value': '780–936 RSD/sat (13–15,6 RSD/min)', 'date': 'avgust 2023', 'source': 'forum.beobuild.rs', 'url': 'https://forum.beobuild.rs/threads/električna-vozila-i-punjači.3889/page-64', 'confidence': 'korisnički podatak'},
   {'what': 'Istorija: raspon cele mreže (izjava operatera)', 'value': '„od 12 dinara na malom sporom punjaču, do 80 dinara na najvećem od 180 kilovata“ po minutu', 'date': 'novembar 2022', 'source': '24sedam.rs (intervju)', 'url': 'https://24sedam.rs/biznis/finansije/173480/negde-besplatno-a-negde-samo-jeftino-sve-vise-e-automobila-u-srbiji-gde-ih-puniti-strujom/vest', 'confidence': 'medij'},
  ],
  'fees': 'Na tri računa iz aplikacije iznos je tačno broj minuta × cena po minutu (npr. 6 × 126,67 = 760,02 RSD) — naknade za pokretanje punjenja nema. Naknada za zauzeće (idle fee): prvih 15 minuta posle završetka punjenja besplatno, zatim 5,00 RSD za svaki započeti minut (Opšti uslovi, na snazi od 26.06.2024). Registracija: početna uplata 3.000 RSD; automatska dopuna 3.000 RSD kad saldo padne ispod 400 RSD. Bez registracije: jednokratno plaćanje karticom preko QR koda na punjaču, fiskalni račun na e-mail.',
  'payment': 'Aplikacija (pripejd saldo), QR kod na punjaču karticom bez registracije, RFID kartica (dostava 2–3 dana), postpejd za pravna lica',
  'roaming': 'Platforma Virta / Hubject — „preko 400.000 punjača“ u Evropi kroz istu aplikaciju; roming se uključuje na zahtev (podrska@chargego.rs). Punjači su vidljivi i u Electromaps-u (Electropass) i u aplikaciji Orion eMobility, gde su skuplji: 22.09.2026 Super Vero Novi Sad u Orionu 197 RSD/min + 140 RSD za priključenje, u aplikaciji Charge&GO 114,17 RSD/min.',
  'support': '011 715 85 99 (pon–pet 8–16) · dežurna linija 24/7 066 803 17 00 · podrska@chargego.rs',
  'sources': [src('https://chargego.rs/', 'chargego.rs — brojači mreže'), src('https://chargego.rs/opsti-uslovi/', 'chargego.rs/opsti-uslovi — naknada za zauzeće'), src('https://chargego.rs/podrska-cesta-pitanja/', 'chargego.rs/podrska-cesta-pitanja — cene, depozit, roming'), src('https://www.omv.rs/sr/mobilnost/elektricni-punjaci/lokacije', 'omv.rs — lokacije i snage'), src('https://chargego.rs/', 'aplikacija Charge&GO — cene po punjaču i računi (snimci ekrana redakcije)'), src('https://evfix.rs/stanice-za-punjenje-ev/naplata-punjenja/mapa-punjaca-novi-sad/', 'evfix.rs — cena Super Vero Novi Sad (02.2025)'), src('https://energetskiportal.rs/platforma-chargego/', 'energetskiportal.rs — ko je operater (03.2021)')],
  'verified': D, 'confidence': 'visoka — cene iz aplikacije i računi redakcije (22.09.2026)',
  'notes': 'Charge&GO i „ChargeGo“ sa elektropunjaci.com su ista kompanija (MT-KOMEX d.o.o., Beograd) — u registru kućnih punjača vodimo je kao <a href="/firme/chargego/">Charge&GO / ChargeGo</a>. Cene u tabeli su iz aplikacije na dan provere; pre punjenja proverite iznos u aplikaciji. U aplikaciji je i punjač u Skoplju (Vero Jumbo, DC 150 kW, 113,63 RSD/min).',
 },
 {
  'slug': 'orion-emobility', 'name': 'Orion eMobility (Orion Telekom)', 'kind': 'cpo', 'order': 2,
  'short': 'Operator mreže i aplikacija za naplatu (CPO + eMSP) telekom-operatera Orion Telekom; upravlja i državnim punjačima JP „Putevi Srbije“ na autoputevima.',
  'website': 'https://oriontelekom.rs/emobility/aplikacija/', 'domain': 'oriontelekom.rs', 'app': 'Orion eMobility (iOS/Android)',
  'city': 'Beograd', 'coverage': 'Srbija; aplikacija pokriva i Crnu Goru, BiH, Hrvatsku, Sloveniju, Severnu Makedoniju, Albaniju (partnerske mreže)',
  'network': '„Infrastruktura od 300 EV punjačnih mesta u zemlji“ i „više od 1.000 EV punjača širom Srbije i regiona“ — navodi operatera bez datuma (marketinška cifra, ne proverena nezavisno)',
  'power': 'AC do 22 kW; DC 20–400 kW (po katalogu opreme); punjači JP „Putevi Srbije“ 40–300 kW',
  'billing': 'Po minutu (na AC punjaču i po satu, npr. 700 RSD za 60 min) + naknada za priključenje; cenovnik po punjaču je u aplikaciji, na sajtu nije objavljen. Za sopstvene punjače aplikacija 22.09.2026 navodi: naknada za priključenje 50 RSD, „cena na min počinje se naplaćivati nakon 3 minuta“, posle punjenja 15 minuta bez naknade, zatim 5 RSD/min za mirovanje.',
  'verdicts': {'cenovnik': 'Nije objavljen — samo u aplikaciji', 'naplata': 'Po minutu + 50 RSD priključenje', 'kwh': 'Ne', 'idle': '5 RSD/min posle 15 min'},
  'vclass': {'cenovnik': 'ask', 'naplata': 'ask', 'kwh': 'no', 'idle': 'yes'},
  'prices': [
   {'what': 'DC 50 kW CHAdeMO — OMV Novi Sad', 'value': '50 RSD/min + 50 RSD priključenje', 'date': D, 'source': 'aplikacija Orion eMobility — snimak ekrana redakcije', 'url': 'https://oriontelekom.rs/emobility/aplikacija/', 'confidence': 'primarni izvor (aplikacija)'},
   {'what': 'AC 22 kW — OMV Novi Sad', 'value': '700 RSD za 60 min (11,67 RSD/min) + 50 RSD', 'date': D, 'source': 'aplikacija Orion eMobility — snimak ekrana redakcije', 'url': 'https://oriontelekom.rs/emobility/aplikacija/', 'confidence': 'primarni izvor (aplikacija)'},
   {'what': 'DC 75 kW CCS — SIRIUS eksterno', 'value': '70 RSD/min + 50 RSD', 'date': D, 'source': 'aplikacija Orion eMobility — snimak ekrana redakcije', 'url': 'https://oriontelekom.rs/emobility/aplikacija/', 'confidence': 'primarni izvor (aplikacija)'},
   {'what': 'DC 50 kW CCS — Škoda Auto Čačak', 'value': '70 RSD/min + 50 RSD', 'date': D, 'source': 'aplikacija Orion eMobility — snimak ekrana redakcije', 'url': 'https://oriontelekom.rs/emobility/aplikacija/', 'confidence': 'primarni izvor (aplikacija)'},
   {'what': 'AC 22 kW — Auto kuća Mikom', 'value': '30 RSD/min + 50 RSD', 'date': D, 'source': 'aplikacija Orion eMobility — snimak ekrana redakcije', 'url': 'https://oriontelekom.rs/emobility/aplikacija/', 'confidence': 'primarni izvor (aplikacija)'},
   {'what': 'Roming, punjač Charge&GO: DC 150 kW, Super Vero Novi Sad', 'value': '197 RSD/min + 140 RSD', 'date': D, 'source': 'aplikacija Orion eMobility — snimak ekrana redakcije', 'url': 'https://oriontelekom.rs/emobility/aplikacija/', 'confidence': 'primarni izvor (aplikacija)'},
   {'what': 'Roming, punjač Charge&GO: DC 120 kW, OMV Borska (Bahtijara Vagabzade)', 'value': '176 RSD/min + 140 RSD', 'date': D, 'source': 'aplikacija Orion eMobility — snimak ekrana redakcije', 'url': 'https://oriontelekom.rs/emobility/aplikacija/', 'confidence': 'primarni izvor (aplikacija)'},
   {'what': 'Roming, punjač Charge&GO: AC 22 kW, Staro Sajmište 29', 'value': '30 RSD/min + 80 RSD', 'date': D, 'source': 'aplikacija Orion eMobility — snimak ekrana redakcije', 'url': 'https://oriontelekom.rs/emobility/aplikacija/', 'confidence': 'primarni izvor (aplikacija)'},
   {'what': 'Istorija: DC 75 kW, OMV Novi Sad (Partizanska)', 'value': '70 RSD/min (4.200 RSD/sat)', 'date': '2024', 'source': 'evfix.rs', 'url': 'https://evfix.rs/stanice-za-punjenje-ev/naplata-punjenja/omv-novi-sad/', 'confidence': 'korisnički podatak'},
   {'what': 'Istorija: DC 50 kW, ista lokacija', 'value': '50 RSD/min (3.000 RSD/sat)', 'date': '2024', 'source': 'evfix.rs', 'url': 'https://evfix.rs/stanice-za-punjenje-ev/naplata-punjenja/omv-novi-sad/', 'confidence': 'korisnički podatak'},
   {'what': 'Istorija: AC 22 kW, ista lokacija', 'value': '11,66 RSD/min (700 RSD/sat)', 'date': '2024', 'source': 'evfix.rs', 'url': 'https://evfix.rs/stanice-za-punjenje-ev/naplata-punjenja/omv-novi-sad/', 'confidence': 'korisnički podatak'},
  ],
  'fees': 'Naknada za priključenje: 50 RSD na sopstvenim punjačima, 80–140 RSD na roming punjačima Charge&GO. Naknada za mirovanje: 5 RSD/min posle 15 minuta na sopstvenim punjačima; na roming punjačima 0 RSD (aplikacija, 22.09.2026). Tokom sesije aplikacija rezerviše na kartici 2.000 RSD (AC punjač) ili 4.000 RSD (DC punjač); naplaćuje se stvarni iznos.',
  'payment': 'Platna kartica u aplikaciji (Visa, MasterCard, Diners, Amex, DinaCard), opcioni pripejd kredit, RFID kartica Orion, QR kod na punjaču; korporativni računi na zahtev',
  'roaming': '„Uvid u lokacije preko 400.000 punjača širom Evrope i sveta“ (partner za roming nije naveden). U aplikaciji su i punjači Charge&GO, skuplji nego u aplikaciji Charge&GO: 22.09.2026 Super Vero Novi Sad 197 RSD/min + 140 RSD, naspram 114,17 RSD/min.',
  'support': '011 4100 333 · support.emobility@oriontelekom.rs',
  'sources': [src('https://oriontelekom.rs/emobility/aplikacija/', 'oriontelekom.rs/emobility/aplikacija — plaćanje, rezervacija na kartici'), src('https://oriontelekom.rs/emobility/kompletna-infrastruktura/', 'oriontelekom.rs — veličina mreže, partneri'), src('https://apps.apple.com/rs/app/orion-emobility/id1615624626', 'App Store — opis aplikacije, zemlje'), src('https://oriontelekom.rs/emobility/aplikacija/', 'aplikacija Orion eMobility — cene po punjaču (snimci ekrana redakcije)'), src('https://evfix.rs/stanice-za-punjenje-ev/naplata-punjenja/omv-novi-sad/', 'evfix.rs — cene OMV Novi Sad (2024)'), src('https://www.putevi-srbije.rs/index.php/en/electric-chargers', 'putevi-srbije.rs — aktivacija državnih punjača kroz Orion aplikaciju')],
  'verified': D, 'confidence': 'visoka — cene iz aplikacije (22.09.2026); veličina mreže je navod operatera',
  'notes': 'OMV Novi Sad je u aplikaciji Orion eMobility i 22.09.2026 (punjači 1128 i 1129), iako na stranici OMV-a uz tu lokaciju stoji aplikacija EasyPark — ista stanica može da se naplaćuje kroz više aplikacija, po različitim cenama. Punjač u Surčinskoj 52 (Garni hotel Mar) aplikacija vodi kao rezervisan za goste hotela. Orion prodaje i kućne punjače: <a href="/firme/orion-emobility/">kartica u registru firmi</a>.',
 },
 {
  'slug': 'putevi-srbije', 'name': 'JP „Putevi Srbije“ — punjači na autoputevima', 'kind': 'drzavni', 'order': 3,
  'short': 'Državni punjači na naplatnim stanicama i odmorištima autoputeva. Punjenje je za sada besplatno; naplata još nije zakonski uređena.',
  'website': 'https://www.putevi-srbije.rs/index.php/en/electric-chargers', 'domain': 'putevi-srbije.rs', 'app': 'Orion eMobility; punjači su vidljivi i u Plug&Share, Virta i Google Maps',
  'city': 'Beograd', 'coverage': 'mreža autoputeva (E75, E70, E80, A2 i drugi)',
  'network': '36 punjača ukupno: 31 u radu, 5 u priključenju, 3 planirana na novim deonicama (sajt JP „Putevi Srbije“, provereno 22.09.2026)',
  'power': 'DC 40–300 kW (+ AC 20–22 kW na delu lokacija); ultrabrzi 175–300 kW na platoima Stara Pazova i Šimanovci',
  'billing': 'Besplatno — „punjenje električnih vozila na postojećim punjačima je trenutno besplatno“ (sajt); priprema se regulativa za uvođenje naplate (B92, 19.06.2026).',
  'verdicts': {'cenovnik': 'Besplatno', 'naplata': 'Bez naplate', 'kwh': '—', 'idle': 'Ne pominje se'},
  'vclass': {'cenovnik': 'yes', 'naplata': 'yes', 'kwh': 'no', 'idle': 'no'},
  'prices': [
   {'what': 'Sve lokacije', 'value': 'Besplatno (0 RSD)', 'date': '22.09.2026', 'source': 'putevi-srbije.rs', 'url': 'https://www.putevi-srbije.rs/index.php/en/electric-chargers', 'confidence': 'primarni izvor'},
  ],
  'fees': 'Nema naknada. Nema objavljenog ograničenja trajanja sesije.',
  'payment': 'Aktivacija kroz aplikaciju Orion eMobility (bez naplate)',
  'roaming': '—',
  'support': '011 4100 333 (tehnička podrška, broj Orion Telekoma)',
  'sources': [src('https://www.putevi-srbije.rs/index.php/en/electric-chargers', 'putevi-srbije.rs — broj punjača, status, besplatno'), src('https://www.b92.net/automobili/garaza/243280/koliko-kosta-punjenje-elektricnog-automobila-u-srbiji-detaljna-racunica-troskova-na-100-kilometara/vest', 'B92, 19.06.2026 — besplatno, naplata u pripremi'), src('https://rs.bloombergadria.com/ekonomija/srbija/84075/drzavni-punjaci-besplatni-elektricnih-vozila-malo/news', 'Bloomberg Adria, 25.07.2025 — naplata nije zakonski regulisana'), src('https://www.palo.rs/punjaci-za-elektricna-kola-na-putevima-u-srbiji/', 'palo.rs — lokacije i snage (medij)'), src('https://byd-auto.rs/blog/gde-napuniti-elektricni-auto-u-srbiji-sve-sto-treba-da-znate/', 'byd-auto.rs — pregled lokacija (16.04.2026)')],
  'verified': D, 'confidence': 'visoka (primarni izvor za broj i besplatnost); lokacije i snage prema medijima',
  'notes': 'Poznate lokacije prema medijima: Subotica (DC 50), Šid–Adaševci (DC 75 + AC 22), Dimitrovgrad (DC 50 / AC 22), Trstenik I i II (DC 50 / AC 20), Preševo (DC 40), Boljkovci, Koševi, Ćićevac, Kruševac, Vrnjačka Banja, Stara Pazova i Šimanovci (175–300 kW), Beograd i Niš (175 kW). Pun spisak sa statusom je na stranici JP „Putevi Srbije“. Vidi i <a href="/javno-punjenje/besplatni-punjaci/">besplatne punjače</a>.',
 },
 {
  'slug': 'tesla', 'name': 'Tesla — Supercharger i Destination Charging', 'kind': 'cpo', 'order': 4,
  'short': 'Dve Supercharger lokacije (Beograd, Aleksinac) i četiri Destination Charging lokacije (hoteli). Cene za Srbiju Tesla ne prikazuje na sajtu.',
  'website': 'https://www.tesla.com/findus/list/superchargers/Serbia', 'domain': 'tesla.com', 'app': 'Tesla (iOS/Android)',
  'city': 'Beograd', 'coverage': 'Beograd (AVA Shopping Park), Aleksinac (E75); Destination: Zlatibor, Beograd',
  'network': 'Supercharger Beograd — AVA Shopping Park, Astrid Lindgren 23: 8 mesta, do 250 kW, 24/7. Supercharger Aleksinac — Bosphorus Hotel, Žitkovački put bb: 4 mesta, do 125 kW, 24/7. Destination Charging: Vila Đokić (Zlatibor), Crowne Plaza Belgrade, Tesla Smart Stay, Square Nine Hotel',
  'power': 'DC do 250 kW (Beograd), do 125 kW (Aleksinac); Destination AC',
  'billing': 'Cena po kWh za Srbiju nije prikazana na tesla.com; obračun i plaćanje idu kroz Tesla aplikaciju/nalog. Da li su Supercharger-i u Srbiji otvoreni za vozila drugih marki — nije potvrđeno.',
  'verdicts': {'cenovnik': 'Nije prikazan za Srbiju', 'naplata': 'Kroz Tesla nalog', 'kwh': 'Ne pominje se', 'idle': 'Po minutu (globalno pravilo)'},
  'vclass': {'cenovnik': 'no', 'naplata': 'ask', 'kwh': 'no', 'idle': 'ask'},
  'prices': [
   {'what': 'Supercharger u Srbiji', 'value': '„besplatno u Srbiji za Tesla vozila“ — navod korisnika', 'date': 'septembar 2023', 'source': 'forum.beobuild.rs', 'url': 'https://forum.beobuild.rs/threads/električna-vozila-i-punjači.3889/', 'confidence': 'korisnički podatak, nije potvrđen'},
  ],
  'fees': 'Tesla globalno naplaćuje idle fee / congestion fee po minutu kad je stanica zauzeta a auto napunjen; iznos za Srbiju nije naveden u Teslinoj tabeli naknada.',
  'payment': 'Tesla aplikacija (platna kartica na nalogu)',
  'roaming': '—',
  'support': 'tesla.com/support',
  'sources': [src('https://www.tesla.com/findus/list/superchargers/Serbia', 'tesla.com — lista Supercharger lokacija u Srbiji'), src('https://www.tesla.com/findus/location/supercharger/belgradeavasupercharger', 'tesla.com — Beograd AVA: 8 mesta, do 250 kW'), src('https://www.tesla.com/en_NZ/findus/list/chargers/Serbia', 'tesla.com — Destination Charging lokacije'), src('https://www.tesla.com/support/charging/supercharger/fees', 'tesla.com — naknade (idle/congestion fee)'), src('https://avashoppingpark.rs/en/ava-shopping-park-part-of-the-tesla-supercharger-network/', 'avashoppingpark.rs — planirano proširenje')],
  'verified': D, 'confidence': 'visoka za lokacije · cene nepoznate',
  'notes': 'AVA Shopping Park najavljuje još 10 Supercharger mesta i „nekoliko generičkih“ punjača za druge marke (bez datuma).',
 },
 {
  'slug': 'omv', 'name': 'OMV Srbija — punjači na benzinskim stanicama', 'kind': 'host', 'order': 5,
  'short': 'Domaćin, ne operator: 24 OMV stanice sa brzim punjačima koje vode partneri — Charge&GO (18 lokacija) i aplikacija EasyPark (6 lokacija). Cene određuju operateri.',
  'website': 'https://www.omv.rs/sr/mobilnost/elektricni-punjaci/lokacije', 'domain': 'omv.rs', 'app': 'Charge&GO ili EasyPark — zavisi od stanice (piše na stubu punjača)',
  'city': 'Beograd', 'coverage': 'Beograd, Novi Sad, Kragujevac, Kruševac, Kraljevo, Vranje, Loznica, Jagodina, Zaječar, koridori E75/E70',
  'network': '24 lokacije (sajt OMV-a, provereno 22.09.2026): Charge&GO — Ada Ciganlija 50 kW, Bačka Topola 1 180, Borska 120, Doljevac 140, Gradina 90, Jagodina 110, Kneževac 120, Kragujevac 150, Kraljevo 2 60, Kruševac 130, Lapovo Sever 100, Lapovo Jug 120, Loznica 120, Martinci 1 180, Metro 240, Obilaznica 1 120, Obilaznica 2 120, Vranje 120, Zaječar 45; EasyPark — Beška 1 75, Bubanj Potok 60, Novi Sad (Partizanska) 75, Ražanj 60, Ruma 75',
  'power': 'DC 45–240 kW',
  'billing': '„Plaćanje usluge je moguće samo preko aplikacije“ — cene i uslovi su operatera (Charge&GO / EasyPark), OMV ih ne objavljuje.',
  'verdicts': {'cenovnik': 'Kod operatera', 'naplata': 'Preko aplikacije partnera', 'kwh': 'Ne', 'idle': 'Kod operatera'},
  'vclass': {'cenovnik': 'ask', 'naplata': 'ask', 'kwh': 'no', 'idle': 'ask'},
  'prices': [
   {'what': 'Charge&GO: DC 240 kW — OMV Zemun park (Novosadski put)', 'value': '126,67 RSD/min', 'date': D, 'source': 'aplikacija Charge&GO — snimak ekrana redakcije', 'url': 'https://chargego.rs/', 'confidence': 'primarni izvor (aplikacija)'},
   {'what': 'Charge&GO: DC 180 kW — OMV Bačka Topola 1', 'value': '114,17 RSD/min', 'date': D, 'source': 'aplikacija Charge&GO — snimak ekrana redakcije', 'url': 'https://chargego.rs/', 'confidence': 'primarni izvor (aplikacija)'},
   {'what': 'Charge&GO: DC 110–120 kW — OMV Kneževac, Borska, Vranje, Palić', 'value': '101,67 RSD/min', 'date': D, 'source': 'aplikacija Charge&GO — snimak ekrana redakcije', 'url': 'https://chargego.rs/', 'confidence': 'primarni izvor (aplikacija)'},
   {'what': 'Charge&GO: DC 50 kW — OMV Ada Ciganlija', 'value': '33,33 RSD/min', 'date': D, 'source': 'aplikacija Charge&GO — snimak ekrana redakcije', 'url': 'https://chargego.rs/', 'confidence': 'primarni izvor (aplikacija)'},
   {'what': 'Orion eMobility: DC 50 kW i AC 22 kW — OMV Novi Sad', 'value': '50 RSD/min · 700 RSD za 60 min; + 50 RSD priključenje', 'date': D, 'source': 'aplikacija Orion eMobility — snimak ekrana redakcije', 'url': 'https://oriontelekom.rs/emobility/aplikacija/', 'confidence': 'primarni izvor (aplikacija)'},
  ],
  'fees': 'Prema uslovima operatera na konkretnoj stanici (vidi Charge&GO).',
  'payment': 'Samo aplikacija partnera (Charge&GO ili EasyPark)',
  'roaming': 'Prema operateru',
  'support': 'omv.rs — kontakt; za punjač: podrška operatera sa stuba',
  'sources': [src('https://www.omv.rs/sr/mobilnost/elektricni-punjaci/lokacije', 'omv.rs — tabela lokacija, snaga i aplikacija'), src('https://www.omv.rs/sr/mobilnost/elektricni-punjaci', 'omv.rs — „plaćanje samo preko aplikacije“, plan eMotion do 2030')],
  'verified': D, 'confidence': 'visoka (primarni izvor)',
  'notes': 'OMV najavljuje integraciju u evropsku mrežu „OMV eMotion“ do 2030; u Srbiji eMotion još ne radi kao operator.',
 },
 {
  'slug': 'easypark', 'name': 'EasyPark — aplikacija na 6 OMV stanica', 'kind': 'app', 'order': 6,
  'short': 'Aplikacija za plaćanje navedena na stranici OMV-a uz 6 stanica. Sajt EasyPark-a za Srbiju sa uslovima punjenja nismo našli — podaci su nepotpuni.',
  'website': 'https://www.omv.rs/sr/mobilnost/elektricni-punjaci/lokacije', 'domain': 'omv.rs (navod)', 'app': 'EasyPark',
  'city': '—', 'coverage': 'OMV Beška 1, Bubanj Potok, Novi Sad (Partizanska), Ražanj, Ruma (+ jedna lokacija koju OMV ne imenuje)',
  'network': '6 OMV lokacija (sajt OMV-a, 22.09.2026)',
  'power': 'DC 60–75 kW',
  'billing': 'Nije objavljeno. Napomena: OMV Novi Sad (Partizanska) je 22.09.2026 dostupan i u aplikaciji Orion eMobility (DC 50 kW 50 RSD/min, AC 22 kW 700 RSD za 60 min, + 50 RSD priključenje) — vidi karticu Orion.',
  'verdicts': {'cenovnik': 'Nije objavljen', 'naplata': 'Ne pominje se', 'kwh': 'Ne pominje se', 'idle': 'Ne pominje se'},
  'vclass': {'cenovnik': 'no', 'naplata': 'no', 'kwh': 'no', 'idle': 'no'},
  'prices': [],
  'fees': 'Nije objavljeno.',
  'payment': 'Aplikacija EasyPark (prema OMV-u)',
  'roaming': '—',
  'support': '—',
  'sources': [src('https://www.omv.rs/sr/mobilnost/elektricni-punjaci/lokacije', 'omv.rs — lokacije sa aplikacijom EasyPark')],
  'verified': D, 'confidence': 'niska — jedini izvor je stranica OMV-a',
  'notes': 'Ako imate podatke sa lica mesta (cena, uslovi), <a href="/ispravka/">javite nam</a> — dopunjujemo sa datumom.',
 },
 {
  'slug': 'nis-gazprom', 'name': 'NIS Petrol / Gazprom — punjači na benzinskim stanicama', 'kind': 'host', 'order': 7,
  'short': 'Domaćin: na delu NIS Petrol i Gazprom stanica rade punjači mreže Charge&GO. Tačan broj stanica sa punjačima NIS ne objavljuje.',
  'website': 'https://www.nisgazprom.rs/', 'domain': 'nisgazprom.rs', 'app': 'Charge&GO',
  'city': 'Novi Sad', 'coverage': 'izabrane NIS Petrol / Gazprom stanice (E75, Beograd, Novi Sad…)',
  'network': 'Broj lokacija nije objavljen. Primeri: NIS Zmaj 1 (A3, Beograd) — CCS2 75 kW, CHAdeMO 50 kW, Type 2 22 kW (Electromaps, 08.2025); 2022: Velika Plana, Stari Banovci, Novi Sad 16, Sokolići 1',
  'power': 'DC 50–75 kW, AC 22 kW (prema zabeleženim lokacijama)',
  'billing': 'Cene i uslovi Charge&GO (po minutu, u aplikaciji); NIS na sajtu objavljuje samo Charge&GO FAQ (decembar 2023).',
  'verdicts': {'cenovnik': 'Kod operatera (Charge&GO)', 'naplata': 'Po minutu (Charge&GO)', 'kwh': 'Ne', 'idle': '5 RSD/min posle 15 min (Charge&GO)'},
  'vclass': {'cenovnik': 'ask', 'naplata': 'ask', 'kwh': 'no', 'idle': 'yes'},
  'prices': [
   {'what': 'Račun, Charge&GO: BS Gazprom Stari Banovci, DC (tarifa 58,33 RSD/min)', 'value': '349,98 RSD za 4,43 kWh ≈ 79 RSD/kWh', 'date': 'avgust 2026', 'source': 'račun u aplikaciji Charge&GO (punjenje redakcije)', 'url': 'https://chargego.rs/', 'confidence': 'primarni izvor (račun)'},
  ],
  'fees': 'Prema uslovima Charge&GO.',
  'payment': 'Aplikacija Charge&GO, QR karticom',
  'roaming': 'Prema Charge&GO',
  'support': 'Charge&GO: 011 715 85 99',
  'sources': [src('https://www.nisgazprom.rs/wp-content/uploads/2023/12/Chargego.pdf', 'nisgazprom.rs — Charge&GO FAQ (12.2023)'), src('https://www.electromaps.com/en/charging-stations/serbia', 'Electromaps — NIS Zmaj 1 (08.2025)'), src('https://energijabalkana.net/u-srbiji-besplatno-punjenje-auta-na-struju-ali-malo-punjaca/', 'energijabalkana.net — prve 4 NIS lokacije (01.2022)')],
  'verified': D, 'confidence': 'srednja — broj lokacija nije objavljen',
  'notes': '',
 },
 {
  'slug': 'emobility-spectra', 'name': 'Emobility (DOO Spectra, Novi Sad)', 'kind': 'cpo', 'order': 8,
  'short': 'Operator mreže punjača (CPO) i pružalac usluga e-mobilnosti sa sopstvenom aplikacijom „Emobility Spectra“; prodaje i ugrađuje AC/DC punjače.',
  'website': 'https://emobility.rs/', 'domain': 'emobility.rs', 'app': 'Emobility Spectra (iOS/Android)',
  'city': 'Novi Sad', 'coverage': 'Novi Sad i Vojvodina (mapa punjača na sajtu)',
  'network': 'Veličina mreže nije objavljena. U aplikaciji (22.09.2026) vidljivi su, između ostalih: JMEV CUBI (DC 90 kW), CITY TAXI Novi Sad (DC 180 kW), Battery Magic (DC 120 kW), GIORGIO Luxury (AC 11 kW), Salaš 265 (AC 17,2 kW).',
  'power': 'AC 11–17,2 kW, DC 90–180 kW (punjači vidljivi u aplikaciji); punjač Battery Magic ima i kineski konektor GB/T',
  'billing': 'Kombinovani obračun: cena po „jedinici punjenja“ (45–60 RSD, zavisi od punjača i tarife) + 1,20 RSD po minutu, PDV uračunat (aplikacija, 22.09.2026). Po objašnjenju u aplikaciji, jedinicu računa punjač iz snage, vremena i profila punjenja; ona nije zakonski overeno merenje i ne odgovara tačno potrošnji u kWh.',
  'verdicts': {'cenovnik': 'Nije objavljen — samo u aplikaciji', 'naplata': 'Po „jedinici“ + po minutu', 'kwh': 'Ne — „jedinica punjenja“', 'idle': '10,20 RSD/min posle 10 min (ECO tarifa)'},
  'vclass': {'cenovnik': 'ask', 'naplata': 'ask', 'kwh': 'no', 'idle': 'yes'},
  'prices': [
   {'what': 'DC 180 kW — CITY TAXI Novi Sad (ECO tarifa)', 'value': '45 RSD po jedinici + 1,20 RSD/min', 'date': D, 'source': 'aplikacija Emobility Spectra — snimak ekrana redakcije', 'url': 'https://emobility.rs/', 'confidence': 'primarni izvor (aplikacija)'},
   {'what': 'DC 120 kW — Battery Magic', 'value': '60 RSD po jedinici + 1,20 RSD/min', 'date': D, 'source': 'aplikacija Emobility Spectra — snimak ekrana redakcije', 'url': 'https://emobility.rs/', 'confidence': 'primarni izvor (aplikacija)'},
   {'what': 'AC 17,2 kW — Salaš 265 (ECO tarifa)', 'value': '45 RSD po jedinici + 1,20 RSD/min', 'date': D, 'source': 'aplikacija Emobility Spectra — snimak ekrana redakcije', 'url': 'https://emobility.rs/', 'confidence': 'primarni izvor (aplikacija)'},
   {'what': 'AC 11 kW — GIORGIO Luxury', 'value': '54 RSD po jedinici + 1,20 RSD/min', 'date': D, 'source': 'aplikacija Emobility Spectra — snimak ekrana redakcije', 'url': 'https://emobility.rs/', 'confidence': 'primarni izvor (aplikacija)'},
  ],
  'fees': 'ECO tarifa: posle završetka punjenja 10 minuta bez naknade, zatim 10,20 RSD/min za zauzeće mesta. Za punjače Battery Magic i GIORGIO Luxury naknada za zauzeće u aplikaciji nije navedena (22.09.2026).',
  'payment': 'Novčanik u aplikaciji (platna kartica), RFID kartica, Apple Wallet',
  'roaming': 'Ne pominje se',
  'support': '021 674 10 33 · Bulevar cara Lazara 88, Novi Sad',
  'sources': [src('https://emobility.rs/', 'emobility.rs — opis usluge, kontakt'), src('https://apps.apple.com/us/app/emobility-spectra/id6476980928', 'App Store — Emobility Spectra (verzija 2026.5.0, 11.06.2026)'), src('https://emobility.rs/', 'aplikacija Emobility Spectra — cene po punjaču (snimci ekrana redakcije)')],
  'verified': D, 'confidence': 'visoka za cene iz aplikacije (22.09.2026) · veličina mreže nepoznata',
  'notes': 'Ista firma je u registru kućnih punjača: <a href="/firme/emobility-d-o-o/">Emobility d.o.o.</a>',
 },
 {
  'slug': 'edrive', 'name': 'eDrive (eMobil, Beograd)', 'kind': 'app', 'order': 9,
  'short': 'Aplikacija za punjenje (eMSP) i softver za vlasnike punjača; deo evropske eRoaming mreže. Sopstvena mreža u Srbiji i cene nisu objavljene.',
  'website': 'https://edrive.co.rs/', 'domain': 'edrive.co.rs', 'app': 'eDrive (iOS/Android)',
  'city': 'Beograd', 'coverage': 'Srbija + eRoaming (≈50.000 punjača u Evropi u bazi, 2023)',
  'network': 'Nije objavljena; 2023: oko 300 korisnika, ≈14 MWh isporučeno (Netokracija, 26.06.2023)',
  'power': '—',
  'billing': 'Nije objavljeno; e-fiskalni računi na e-mail.',
  'verdicts': {'cenovnik': 'Nije objavljen', 'naplata': 'Ne pominje se', 'kwh': 'Ne pominje se', 'idle': 'Ne pominje se'},
  'vclass': {'cenovnik': 'no', 'naplata': 'no', 'kwh': 'no', 'idle': 'no'},
  'prices': [],
  'fees': 'Nije objavljeno.',
  'payment': 'Aplikacija',
  'roaming': '„Deo najveće eRoaming mreže u Evropi“ (partner nije imenovan na sajtu)',
  'support': 'edrive.co.rs — kontakt',
  'sources': [src('https://edrive.co.rs/', 'edrive.co.rs'), src('https://www.netokracija.rs/edrive-aplikacija-208889', 'netokracija.rs — predstavljanje aplikacije (26.06.2023)')],
  'verified': D, 'confidence': 'niska — podaci iz 2023, aktuelnost nije potvrđena',
  'notes': 'U registru kućnih punjača: <a href="/firme/edrive/">eDrive</a>.',
 },
 {
  'slug': 'lidl-echarge', 'name': 'Lidl eCharge — Novi Sad, Liman', 'kind': 'besplatno', 'order': 10,
  'short': 'Besplatno punjenje na parkingu Lidl prodavnice u Novom Sadu (Ive Andrića 16) tokom radnog vremena, do 60 minuta dnevno.',
  'website': 'https://kompanija.lidl.rs/press-centar/subitems/saopstenja-za-medije/2022/besplatno-punjenje-e-automobila-u-lidlu-na-limanu', 'domain': 'lidl.rs', 'app': 'Lidl eCharge / bilo koja RFID kartica',
  'city': 'Novi Sad', 'coverage': 'jedna lokacija (Liman); druge Lidl prodavnice sa punjačima nisu potvrđene',
  'network': '2 mesta za punjenje: DC do 20 kW (CCS / CHAdeMO) i AC 11 kW',
  'power': 'DC 20 kW, AC 11 kW',
  'billing': 'Besplatno tokom radnog vremena prodavnice (svakog dana 08–22), najviše 60 minuta dnevno.',
  'verdicts': {'cenovnik': 'Besplatno', 'naplata': 'Bez naplate', 'kwh': '—', 'idle': 'Limit 60 min/dan'},
  'vclass': {'cenovnik': 'yes', 'naplata': 'yes', 'kwh': 'no', 'idle': 'ask'},
  'prices': [{'what': 'Punjenje', 'value': 'Besplatno, max 60 min dnevno', 'date': '2022 (saopštenje) / 2024 (evfix.rs)', 'source': 'lidl.rs, evfix.rs', 'url': 'https://evfix.rs/stanice-za-punjenje-ev/besplatno-punjenje/lidl-echarge/', 'confidence': 'primarni izvor + korisnik'}],
  'fees': 'Nema; važi ograničenje 60 minuta dnevno.',
  'payment': 'Aktivacija RFID karticom ili aplikacijom Lidl eCharge',
  'roaming': '—',
  'support': 'kompanija.lidl.rs',
  'sources': [src('https://kompanija.lidl.rs/press-centar/subitems/saopstenja-za-medije/2022/besplatno-punjenje-e-automobila-u-lidlu-na-limanu', 'lidl.rs — saopštenje (2022)'), src('https://evfix.rs/stanice-za-punjenje-ev/besplatno-punjenje/lidl-echarge/', 'evfix.rs — uslovi i iskustvo (2024)')],
  'verified': D, 'confidence': 'srednja — saopštenje je iz 2022, potvrda korisnika iz 2024',
  'notes': '',
 },
 {
  'slug': 'parking-servis-beograd', 'name': 'JKP „Parking servis“ Beograd — punjači u garažama', 'kind': 'besplatno', 'order': 11,
  'short': 'AC punjači u javnim garažama u Beogradu: punjenje se ne naplaćuje, plaća se parkiranje. Podaci o tarifi su iz 2021. godine.',
  'website': 'https://www.parking-servis.co.rs/eng/garaza-obilicev-venac', 'domain': 'parking-servis.co.rs', 'app': '— (kabl kod obezbeđenja garaže)',
  'city': 'Beograd', 'coverage': 'garaža Obilićev venac (6 mesta), Pionirski park (2), Međunarodni carinski terminal (2 + 6 za teretna)',
  'network': 'Obilićev venac: 6 mesta sa punjačem (sajt garaže); Schneider EVlink 22 kW AC, Type 2 — 2 mesta na nivou 1 i 4 na nivou 5 (PlugShare)',
  'power': 'AC 22 kW',
  'billing': 'Punjenje bez naknade; naplaćuje se parkiranje — 2021: 100 RSD po započetom satu za električne automobile (120 RSD za ostale). Aktuelni cenovnik garaža za 2026. nismo mogli da proverimo (sajt blokira automatsko čitanje).',
  'verdicts': {'cenovnik': 'Plaća se samo parking', 'naplata': 'Kroz parking', 'kwh': '—', 'idle': 'Ne pominje se'},
  'vclass': {'cenovnik': 'yes', 'naplata': 'ask', 'kwh': 'no', 'idle': 'no'},
  'prices': [{'what': 'Parkiranje EV u garaži Obilićev venac', 'value': '100 RSD/započeti sat (punjenje uključeno)', 'date': 'oktobar 2021', 'source': '24sedam.rs', 'url': 'https://24sedam.rs/beograd/vesti/85803/besplatna-voznja-ali-samo-uz-automobil-na-struju-gde-u-beogradu-naci-punjace-za-elektricna-vozila/vest', 'confidence': 'medij, zastarelo'}],
  'fees': 'Samo parkiranje po cenovniku garaže.',
  'payment': 'Naplata parkinga u garaži',
  'roaming': '—',
  'support': 'parking-servis.co.rs',
  'sources': [src('https://www.parking-servis.co.rs/eng/garaza-obilicev-venac', 'parking-servis.co.rs — garaža Obilićev venac (6 mesta sa punjačem)'), src('https://www.plugshare.com/location/121438', 'PlugShare — oprema i raspored mesta (korisnici)'), src('https://24sedam.rs/beograd/vesti/85803/besplatna-voznja-ali-samo-uz-automobil-na-struju-gde-u-beogradu-naci-punjace-za-elektricna-vozila/vest', '24sedam.rs — garaže sa punjačima i cena parkinga za EV (29.10.2021)')],
  'verified': D, 'confidence': 'srednja za postojanje · niska za tarifu (2021)',
  'notes': 'Planirane lokacije iz 2021 (Masarikova, Zeleni venac, Belvil) nismo proverili.',
 },
]

KIND_LABEL = {'cpo': 'Operator mreže + aplikacija', 'host': 'Domaćin (benzinske stanice)', 'drzavni': 'Državni punjači', 'besplatno': 'Besplatno punjenje', 'app': 'Aplikacija za plaćanje'}
CARD = {
 'chargego': '79 punjača · 16,67–126,67 RSD/min',
 'orion-emobility': '11,67–70 RSD/min + 50 RSD po sesiji',
 'putevi-srbije': '36 punjača, 31 u radu · besplatno',
 'tesla': '2 Supercharger lokacije · do 250 kW',
 'omv': '24 stanice · DC 45–240 kW',
 'easypark': '6 OMV stanica · DC 60–75 kW',
 'nis-gazprom': 'broj lokacija nije objavljen',
 'emobility-spectra': '45–60 RSD po „jedinici“ + 1,20 RSD/min',
 'edrive': 'sopstvena mreža nije objavljena',
 'lidl-echarge': 'Novi Sad, Liman · do 60 min dnevno',
 'parking-servis-beograd': '3 garaže · plaća se samo parking',
}
for o in OPS:
    o['card'] = CARD[o['slug']]
    o['kind_label'] = KIND_LABEL[o['kind']]
    o['publish'] = True
    (OUT / f"{o['slug']}.json").write_text(json.dumps(o, ensure_ascii=False, indent=1), encoding='utf-8')
print('written', len(OPS), 'operators to', OUT)
