# -*- coding: utf-8 -*-
"""What is due for re-checking on blokvolt.rs.

Usage: python3 scripts/due.py [--date DD.MM.YYYY] [--ahead DAYS]

Reads the check dates that already live in the content files and prints what is overdue or due
within --ahead days (default 10). Sources of truth:
  content/podaci/*.md, content/javno/*.md      front matter `next_check` (+ `updated`)
  content/javno/indeks-cena.json                `next_check` (month name allowed, e.g. "oktobar 2026")
  content/data/kalkulator.json                  fuel.date / fuel.valid_to, public_checked, EPS source dates
  content/data/ev-modeli.json                   `next_check`
  content/data/wallbox-modeli.json              `next_check` (device prices, mirrors the firm register)
  content/data/kalkulator-zgrada.json           `next_check` (MID meter prices, calculator defaults)
  content/data/site.json                        `firms_checked` (full firm register revision, every ~90 days)
  content/firme/*.json                          `verified` per firm (published) and leads (group L, publish=false)
  content/operateri/*.json                      `verified` per network
Plus fixed calendar items (fuel every Friday, OIE fee in December, subsidy deadline, …).
Exit code is always 0; the report is for the person or session doing the update."""
import argparse, datetime as dt, glob, json, re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MONTHS = {'januar': 1, 'februar': 2, 'mart': 3, 'april': 4, 'maj': 5, 'jun': 6, 'jul': 7, 'avgust': 8,
          'septembar': 9, 'oktobar': 10, 'novembar': 11, 'decembar': 12}

def parse(s):
    """'15.10.2026', '15.10.2026 (note)', 'oktobar 2026' -> date (month -> 1st of month); None if unknown."""
    if not s:
        return None
    s = str(s).strip().lower()
    m = re.match(r'(\d{1,2})\.(\d{1,2})\.(\d{4})', s)
    if m:
        return dt.date(int(m.group(3)), int(m.group(2)), int(m.group(1)))
    m = re.match(r'([a-zčćšđž]+)\s+(\d{4})', s)
    if m and m.group(1) in MONTHS:
        return dt.date(int(m.group(2)), MONTHS[m.group(1)], 1)
    return None

def fm(path):
    t = Path(path).read_text(encoding='utf-8')
    if not t.startswith('---'):
        return {}
    head = t.split('---', 2)[1]
    out = {}
    for line in head.splitlines():
        if ':' in line:
            k, v = line.split(':', 1)
            out[k.strip()] = v.strip()
    return out

def fmt(d):
    return d.strftime('%d.%m.%Y') if d else '?'

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--date', help='today as DD.MM.YYYY (default: system date)')
    ap.add_argument('--ahead', type=int, default=10)
    a = ap.parse_args()
    today = parse(a.date) if a.date else dt.date.today()
    horizon = today + dt.timedelta(days=a.ahead)
    due, soon, info = [], [], []

    def check(when, label, what):
        if when is None:
            info.append(f'no parsable date: {label} — {what}')
        elif when <= today:
            due.append((when, f'[overdue since {fmt(when)}] {label} — {what}'))
        elif when <= horizon:
            soon.append((when, f'[due {fmt(when)}] {label} — {what}'))

    # 1) markdown pages
    for p in sorted(glob.glob(str(ROOT / 'content' / 'podaci' / '*.md'))) + sorted(glob.glob(str(ROOT / 'content' / 'javno' / '*.md'))):
        m = fm(p)
        if 'next_check' not in m:
            continue
        rel = str(Path(p).relative_to(ROOT))
        extra = ''
        note = re.sub(r'^\d{1,2}\.\d{1,2}\.\d{4}\s*', '', m['next_check'])
        if note:
            extra = f' {note}'
        gen = ' (generated by scripts/gen_ev_modeli.py from content/data/ev-modeli.json)' if 'cene-elektricnih-automobila' in rel else ''
        check(parse(m['next_check']), rel + gen, f"page updated {m.get('updated', '?')}{extra}")

    # 2) public charging price index
    idx = json.load(open(ROOT / 'content' / 'javno' / 'indeks-cena.json', encoding='utf-8'))
    check(parse(idx.get('next_check')), 'content/javno/indeks-cena.json',
          f"public charging price index, updated {idx.get('updated')} — app screenshots/receipts from the user + public sources")

    # 3) calculator data
    c = json.load(open(ROOT / 'content' / 'data' / 'kalkulator.json', encoding='utf-8'))
    fd = parse(c['fuel'].get('date'))
    check(fd + dt.timedelta(days=14) if fd else None, 'content/data/kalkulator.json fuel',
          f"fuel prices from {c['fuel'].get('date')} (benzin {c['fuel'].get('benzin')}, dizel {c['fuel'].get('dizel')}); new max prices every Friday")
    pc = parse(c.get('public_checked'))
    check(pc + dt.timedelta(days=35) if pc else None, 'content/data/kalkulator.json public',
          f"public charging prices for the calculator (dc/ac), checked {c.get('public_checked')} — follow indeks-cena.json")
    ec = parse(c.get('checked'))
    check(ec + dt.timedelta(days=30) if ec else None, 'content/data/kalkulator.json eps',
          f"EPS regulated tariffs valid from {c['eps'].get('valid_from')}, OIE {c['eps'].get('oie')}, snaga {c['eps'].get('snaga_rsd_kw')} — checked {c.get('checked')}")

    # 4) EV prices data
    ev = json.load(open(ROOT / 'content' / 'data' / 'ev-modeli.json', encoding='utf-8'))
    check(parse(ev.get('next_check')), 'content/data/ev-modeli.json',
          f"EV list prices at importers, checked {ev.get('checked')}; after editing run scripts/gen_ev_modeli.py")

    # 4b) wallbox model prices and the building calculator
    wb = json.load(open(ROOT / 'content' / 'data' / 'wallbox-modeli.json', encoding='utf-8'))
    check(parse(wb.get('next_check')), 'content/data/wallbox-modeli.json',
          f"device prices of {len(wb['rows'])} models, checked {wb.get('checked')}; re-derive from the firm register, then run scripts/gen_wallbox.py")
    zg = json.load(open(ROOT / 'content' / 'data' / 'kalkulator-zgrada.json', encoding='utf-8'))
    check(parse(zg.get('next_check')), 'content/data/kalkulator-zgrada.json',
          f"building-billing calculator defaults and MID meter prices, checked {zg.get('checked')}")

    # 5) firm register
    site = json.load(open(ROOT / 'content' / 'data' / 'site.json', encoding='utf-8'))
    fc = parse(site.get('firms_checked'))
    firms = [json.load(open(p, encoding='utf-8')) for p in sorted(glob.glob(str(ROOT / 'content' / 'firme' / '*.json')))]
    pub = [f for f in firms if f.get('publish')]
    leads = [f for f in firms if not f.get('publish')]
    old = [f for f in pub if (parse(f.get('verified')) or dt.date.min) + dt.timedelta(days=90) <= horizon]
    check(fc + dt.timedelta(days=90) if fc else None, 'content/data/site.json firms_checked',
          f"full firm register revision ({len(pub)} published firms, {len(leads)} leads waiting); last {site.get('firms_checked')}")
    if old:
        info.append(f"{len(old)} published firms verified >90 days ago by the horizon: " + ', '.join(f"{f.get('name')} ({f.get('verified')})" for f in old[:60]))

    # 6) operators
    for p in sorted(glob.glob(str(ROOT / 'content' / 'operateri' / '*.json'))):
        o = json.load(open(p, encoding='utf-8'))
        v = parse(o.get('verified'))
        check(v + dt.timedelta(days=35) if v else None, str(Path(p).relative_to(ROOT)),
              f"network card {o.get('name')}, verified {o.get('verified')}")

    # 7) calendar items
    if today.weekday() == 4 or (fd and (today - fd).days >= 7):
        info.append('fuel: new maximum retail prices are published every Friday (Ministarstvo unutrašnje i spoljne trgovine)')
    if today.month in (12, 1):
        info.append('December/January: OIE fee (naknada za podsticaj povlašćenih proizvođača) for the next year, EPS price changes from 1 January, the "plava zona do 1.200 kWh" rule was announced only until the end of 2026')
    sub_deadline = dt.date(2026, 12, 1)
    if today <= sub_deadline + dt.timedelta(days=31):
        info.append(f'subsidies 2026: application deadline 01.12.2026 — check budget status and any extension ({(sub_deadline - today).days} days left)')
    if today.month in (1, 4, 7, 10):
        info.append('new quarter: SAUVD/ABS quarterly registration figures usually appear 3–6 weeks after the quarter ends (content/podaci/statistika-ev-srbija.md + home stats in content/data/site.json)')

    print(f'BlokVolt due report — {fmt(today)} (horizon +{a.ahead} days)')
    print(f'\nOVERDUE ({len(due)})')
    for _, line in sorted(due):
        print('  ' + line)
    print(f'\nDUE SOON ({len(soon)})')
    for _, line in sorted(soon):
        print('  ' + line)
    print('\nNOTES')
    for line in info:
        print('  - ' + line)

if __name__ == '__main__':
    main()
